disabled_rules:
  - dynamic_inline
  - private_unit_test
  - type_body_length
  - valid_ibinspectable

opt_in_rules:
  - empty_count
  - closure_spacing
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - empty_string
  - fallthrough
  - fatal_error_message
  - first_where
  - joined_default_parameter
  - multiline_arguments
  - multiline_function_chains
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - private_action
  - private_outlet
  - required_enum_case
  - sorted_first_last
  - vertical_parameter_alignment_on_call
  - yoda_condition
  - array_init
  - explicit_init
  - function_default_parameter_at_end
  - prohibited_super_call
  - redundant_nil_coalescing
  - strict_fileprivate

excluded:
  - Pods
attributes:
  severity: error
closing_brace:
  severity: error
closure_end_indentation:
  severity: error
colon:
  severity: error
  flexible_right_spacing: false
  apply_to_dictionaries: true
comma:
  severity: error
conditional_returns_on_newline:
  severity: error
control_statement:
  severity: error
cyclomatic_complexity:
  - 7 #warning
  - 8 #error
empty_count:
  severity: error
empty_parameters:
  severity: error
explicit_init:
  severity: error
file_length:
  - 300 #warning
  - 500 #error
force_cast:
  severity: error
force_try:
  severity: error
force_unwrapping:
  severity: error
function_body_length:
  - 50 #warning
  - 70 #error
function_parameter_count:
  - 5 #warning
  - 6 #error
implicit_getter:
  severity: error
large_tuple:
  - 3 #warning
  - 5 #error
leading_whitespace:
  severity: error
legacy_cggeometry_functions:
  severity: error
legacy_constant:
  severity: error
legacy_constructor:
  severity: error
legacy_nsgeometry_functions:
  severity: error
line_length:
  - 120 #warning
  - 120 #error
mark:
  severity: error
nesting:
  severity: error
nimble_operator:
  severity: error
opening_brace:
  severity: error
operator_usage_whitespace:
  severity: error
operator_whitespace:
  severity: error
overridden_super_call:
  severity: error
redundant_nil_coalescing:
  severity: error
redundant_optional_initialization:
  severity: error
redundant_string_enum_value:
  severity: error
redundant_void_return:
  severity: error
return_arrow_whitespace:
  severity: error
switch_case_on_newline:
  severity: error
syntactic_sugar:
  severity: error
todo:
  severity: error
trailing_comma:
  severity: error
trailing_newline:
  severity: error
trailing_semicolon:
  severity: error
trailing_whitespace:
  severity: error
type_name:
  severity: error
unused_closure_parameter:
  severity: error
identifier_name:
  min_length: 2
  severity: error
vertical_parameter_alignment:
  severity: error
vertical_whitespace:
  severity: error
void_return:
  severity: error
weak_delegate:
  severity: error
lower_acl_than_parent:
  severity: error
first_where:
  severity: error
private_action:
  severity: error
private_outlet:
  severity: error
closure_spacing:
  severity: error
multiline_function_chains:
  severity: error
array_init:
  severity: error
statement_position:
  severity: error
unused_enumerated:
  severity: error
vertical_parameter_alignment_on_call:
  severity: error
strict_fileprivate:
  severity: error
empty_string:
  severity: error
empty_count:
  severity: error
unneeded_break_in_switch:
  severity: error
fatal_error_message:
  severity: error
empty_parentheses_with_trailing_closure:
  severity: error
contains_over_first_not_nil:
  severity: error
